### ISSUE TITLE
Tokenizing strings with '='

### ISSUE THREAD

**Issue by YannDubs** [magizbox/underthesea#159]
Hey I just had some issues with tokenization because of the `=` sign.

I have tested all the punctuations these punctuations : `!"#$%&\'()*+,-./:;<=>?@[\\]^_{|}~ ` and the `=` seems to be the only one to create a bug. 

Here's the error:
![screen shot 2017-11-02 at 4 47 33 pm](https://user-images.githubusercontent.com/24327668/32317230-1268b4b6-bfee-11e7-82d6-fc87b86b5afe.png)

I am using 
* CentOS 7: centos-release-7-4.1708.el7.centos.x86_64
* Pyhton 3.6.3

BTW: thanks for the great package 💯

**Comment by rain1024** [comment]
Hi @YannDubs, please provide me your input string?

**Comment by YannDubs** [comment]
Anything that contains a '='.

example (I don't speak Vietnamese at all): 

```
from underthesea import word_sent
txt = 'Tài xế = bị'
word_sent(txt)
```

but even `txt = '='` throws the error.

**Comment by rain1024** [comment]
@YannDubs I am fixing this issue. Thanks for your report.

This error occurs because I use split function to extract features (for example `T[0]=Tài xế`, `T[1]==`, `T[2]=bị`), with feature `T[1]==`, k.split('=') has only one element :(

**Comment by rain1024** [comment]
The pull request pass CI test. So I have merged it into master.

You can update `underthesea` package with these command

```
pip uninstall -y underthesea
pip install pip install https://github.com/magizbox/underthesea/archive/master.zip
```
