### ISSUE TITLE
Use unicode compose form

### ISSUE THREAD

**Issue by YannDubs** [magizbox/underthesea#161]
Hi :)

The tokenizer doesn't work with glyphs in decomposed form (multiple codepoints). You should maybe think of converting from decomposed to composed form before giving the string to your algorithm.

Example:
```
txt_d='yếu'    
txt_c='yếu'    
print(word_sent(txt_d))
# output: ['yê', '́', 'u']
print(word_sent(txt_c))
# output: ['yếu']
```

Simple workaround: normalize by using compose form:
```
import unicodedata
txt_d=unicodedata.normalize('NFC', txt_d) 
txt_c=unicodedata.normalize('NFC', txt_c)  
print(word_sent(txt_d))
# output: ['yếu']
print(word_sent(txt_c))
# output: ['yếu']
```

I am using 
* CentOS 7: centos-release-7-4.1708.el7.centos.x86_64
* Pyhton 3.6.3

As always keep up with the good work (and I'm sorry I don't have much time to contribute now :( )

**Comment by rain1024** [comment]
🙌 I already had [Text](https://github.com/magizbox/underthesea/blob/master/underthesea/feature_engineering/text.py) function for this issue. But I assume before user will use it before word_sent. I think add it by default is a good idea.

**Comment by YannDubs** [comment]
Sorry didn't realize :/ I think it might be a good idea, it won't really change your performances so I don't see why not to :)

**Comment by rain1024** [comment]
I merged pull request. So every text pass to `word_sent` function is in unicode NFC normalization form.

You can update `underthesea` package (again) with these command

```
pip uninstall -y underthesea
pip install https://github.com/magizbox/underthesea/archive/master.zip
```
