### ISSUE TITLE
word_sent ValueError: dictionary update sequence element #2 has length 3; 2 is required

### ISSUE THREAD

**Issue by tienduccao** [magizbox/underthesea#164]
Hi, I encountered an error `ValueError: dictionary update sequence element #2 has length 3; 2 is required` when calling `word_sent('=))')`

**Comment by rain1024** [comment]
@tienduccao Can you provide a simple example to reproduce this error? What is your code?

**Comment by tienduccao** [comment]
@rain1024 the example was included in the description :D.
```
from underthesea import word_sent
word_sent('=))')
```

**Comment by tienduccao** [comment]
I use python 3.6

**Comment by rain1024** [comment]
It is the same with #159. 

You can update latest underthesea package with these command to overcome this issue

```
pip uninstall -y underthesea
pip install https://github.com/magizbox/underthesea/archive/master.zip
```

**Comment by tienduccao** [comment]
I'm using the following version 
```
pip show underthesea
Name: underthesea
Version: 1.1.5
```
Is it the latest one?
And my example is ``word_sent('=))')`` not ``word_sent('=')`` as #159

**Comment by tienduccao** [comment]
It's weird. I can't reproduce this error when install the library directly as you said.
But it happened when installing underthesea using virtualenv (version 1.1.5)

**Comment by tienduccao** [comment]
Update: `pip install https://github.com/magizbox/underthesea/archive/master.zip` works with/without virtualenv.
But 'pip install underthesea' with virtualenv/Python 3 creates this issue

**Comment by rain1024** [comment]
@tienduccao 

`pip install underthesea` will install the `stable` version in pypi, which resolve [underthesea 1.1.5](https://pypi.python.org/pypi/underthesea)

`pip install https://github.com/magizbox/underthesea/archive/master.zip` will install `latest` version of `underthesea` hosted in github, which I have already fixed this issue.

**Comment by tienduccao** [comment]
Got it. Thanks for your help.

**Comment by rain1024** [comment]
@tienduccao see you in next release
