### ISSUE TITLE
word_sent: dictionary update sequence element #4 has length 3; 2 is required

### ISSUE THREAD

**Issue by ttpro1995** [magizbox/underthesea#168]
How to reproduce: 

```
from underthesea import word_sent
word_sent("Hãng tin CNN công bố thống kê cho thấy Will + Kate = sự kiện lớn thứ 6 trên Internet từ trước đến nay.")
```
Give exception
ValueError: dictionary update sequence element #4 has length 3; 2 is required

**Comment by rain1024** [comment]
It is the same with #159 #164 

You can update latest underthesea package with these command to overcome this issue

```
pip uninstall -y underthesea
pip install https://github.com/magizbox/underthesea/archive/master.zip
```

**Comment by ttpro1995** [comment]
Previously, I was install from `pypi`
Remove pip version and install lastest version from Github (as @rain1024  mention) fixed the problem

**Comment by rain1024** [comment]
PS: Stable version 1.1.6 will be released this week :D
