### ISSUE TITLE
How to use my own data to train word_sent ?

### ISSUE THREAD

**Issue by ttpro1995** [magizbox/underthesea#169]
I would like to use my own data to train  word_sent 
How should I config underthesea to work with my data ?

**Comment by rain1024** [comment]
For each problem, we create a separated project to preprocess data, train and validate model. Please check repositories in https://github.com/undertheseanlp/

For example, in `word segmentation` problem, you can fork this project https://github.com/undertheseanlp/word_sent. 

Next steps:

1. Collect data: put your raw data in a new folder in [`raw folder` ](https://github.com/undertheseanlp/word_sent/tree/master/eda)
2. Prepare data: Write a script to convert raw data to corpus, put it in `corpus` folder, corpus must be in CONLL format.
3. Explore data analysis: create a new file in [`eda` folder](https://github.com/undertheseanlp/word_sent/tree/master/eda)
4. Run `main.py` to train your model
