### ISSUE TITLE
import fasttest in model_fasttext.py (classification) error

### ISSUE THREAD

**Issue by minhtrung995** [magizbox/underthesea#172]
When I import `classify`  function, it returns "cannot import name 'classify'". I try to import whole module `classification` and find out this problems
![image](https://user-images.githubusercontent.com/16595541/34641952-2364590e-f33e-11e7-98b5-0914ec64a0eb.png)

I check the file `model_fasttext.py` and it's really import package `fasttext` without including it in requirements

**Comment by rain1024** [comment]
You should install `fasttext` and download pretrained model to use classify module. Please follow the command lines which suggest in documentation https://github.com/magizbox/underthesea/blob/master/README.rst#5-text-classification

````
$ pip install Cython
$ pip install future scipy numpy scikit-learn
$ pip install -U fasttext --no-cache-dir --no-deps --force-reinstall
$ underthesea data
````

**Comment by minhtrung995** [comment]
I do it and the code run well. But from the [ your docs  ](http://underthesea.readthedocs.io/en/latest/package_reference.html#classify), it doesn't contain the above code. You should add it to the docs too. Thank you

**Comment by rain1024** [comment]
@minhtrung995 [Documention in readthedocs](http://underthesea.readthedocs.io/en/latest/package_reference.html#classify) is already updated. Thank you for mentioning about it.
