### ISSUE TITLE
incorrect url in  Vietnamese-NLP-Tools wiki

### ISSUE THREAD

**Issue by ttpro1995** [magizbox/underthesea#175]
https://github.com/magizbox/underthesea/wiki/Vietnamese-NLP-Tools
At Word segmentation section.
datquocnguyen/RDRsegmenter - A Fast and Accurate Vietnamese Word Segmenter by NQ Dat (2017)  

Url to datquocnguyen/RDRsegmenter  is incorrected. It's link to https://github.com/phongnt570/UETsegmenter , which is UETsegmenter - a toolkit for Vietnamese word segmentation by NT Phong (2016) java 

Suggest fix datquocnguyen/RDRsegmenter  => https://github.com/datquocnguyen/RDRsegmenter

**Comment by rain1024** [comment]
Wiki is updated. Thanks for your suggestion.
