### ISSUE TITLE
error when using classify

### ISSUE THREAD

**Issue by AlexBlack2202** [magizbox/underthesea#176]
When i user command "classify("Hội đồng tư vấn kinh doanh Asean vinh danh giải thưởng quốc tế")", it show the error: 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\TEST\AppData\Local\Programs\Python\Python36\lib\site-packages\underthesea\classification\__init__.py", line 43, in classify
>     return clf.predict(X)
>   File "C:\Users\TEST\AppData\Local\Programs\Python\Python36\lib\site-packages\underthesea\classification\model_fasttext.py", line 73, in predict
>     y_pred = [self.tranform_output(item) for item in y_pred]
>   File "C:\Users\TEST\AppData\Local\Programs\Python\Python36\lib\site-packages\underthesea\classification\model_fasttext.py", line 73, in <listcomp>
>     y_pred = [self.tranform_output(item) for item in y_pred]
>   File "C:\Users\TEST\AppData\Local\Programs\Python\Python36\lib\site-packages\underthesea\classification\model_fasttext.py", line 66, in tranform_output
>     y = y[0].replace("__label__", "")
> IndexError: list index out of range

How can i fix it. Thanks.

**Comment by rain1024** [comment]
@AlexBlack2202  What version of underthesea are you using?

I re-test classify module with these commands below and it works

```
conda create -n underthesea_test python=3.5
source activate underthesea_test
pip install underthesea

pip install Cython
pip install future scipy numpy scikit-learn
pip install -U fasttext --no-cache-dir --no-deps --force-reinstall
underthesea data
```

```
$ python
Python 3.5.5 |Anaconda, Inc.| (default, Mar  9 2018, 19:48:53) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from underthesea import classify
>>> classify("Hội đồng tư vấn kinh doanh Asean vinh danh giải thưởng quốc tế")
['Kinh doanh']
```

**Comment by AlexBlack2202** [comment]
@rain1024  Thank you for your reply.
My underthesea is 1.1.5
>>> import underthesea
>>> underthesea .__version__
'1.1.5'

**Comment by rain1024** [comment]
Did you test my suggestion in your branch new conda environment?

Does it work?

**Comment by AlexBlack2202** [comment]
Hi  @rain1024 
I do not use conda, i use purge python 3.6.3

> Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.

**Comment by rain1024** [comment]
I think you should re-install underthesea and follow my steps above.

**Comment by AlexBlack2202** [comment]
Thank @rain1024 
I have installed in another computer with anaconda. And it still have that problem.

looking deeply in your  file model_fasttext.py and i've got something

 

> import fasttext
> model= fasttext.load_model("fasttext.model")
> dir (model)
> ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_model', 'bucket', 'dim', 'encoding', 'epoch', 'label_prefix', 'labels', 'loss_name', 'lr_update_rate', 'maxn', 'min_count', 'minn', 'model_name', 'neg', 'predict', 'predict_proba', 't', 'test', 'word_ngrams', 'ws']
> //I load model successfull
> 
> model.predict("HLV ngoại đòi gần tỷ mỗi tháng dẫn dắt tuyển Việt Nam")
> [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]

It return a list of empty list. So when do .replace("__label__", "") it wrong.

i check the fasttext version in my computer

> import pkg_resources
> >>> pkg_resources.get_distribution("fasttext").version
> '0.8.3'

I think it is not compatiple of my fasttext version and your model. can you please tell me your fasttext version?

**Comment by rain1024** [comment]
@AlexBlack2202 

Here are my dependencies

```
$ source activate underthesea_test
$ pip freeze
certifi==2018.1.18
click==6.7
Cython==0.27.3
fasttext==0.8.3
future==0.16.0
joblib==0.11
languageflow==1.1.6rc2
numpy==1.14.1
pandas==0.22.0
python-crfsuite==0.9.5
python-dateutil==2.7.0
pytz==2018.3
scikit-learn==0.19.0
scipy==1.0.0
six==1.11.0
underthesea==1.1.6
xgboost==0.7.post3
```

According to this result, I have fasttext 0.8.3 in my environment

**Comment by AlexBlack2202** [comment]
@rain1024 
I use windown 10. When i use in bash window 10 (base on ubuntu). It run successfull. 
But it can not run in window 10. The only thing diffirence is xgboost. In my window is xgboost==0.7 and in bash is xgboost==0.7.post3

**Comment by AlexBlack2202** [comment]
I read in fasttext issue and there is someone have this problem when load model in windows. This is not underthesea error. 
The problenm is in this link 
https://github.com/salestock/fastText.py/issues/112

**Comment by rain1024** [comment]
@AlexBlack2202 Thanks for your clarification. 

I will close this issue here
