### ISSUE TITLE
How to retrain sentiment model with my own data?

### ISSUE THREAD

**Issue by duyluandethuong** [magizbox/underthesea#177]
I have a set of text with sentiment classification in technology industry, but I currently do not know how to retrain your model. I saw that you are using `bank` dataset for training, can I replace it with my own data?

Please give me some keyword so I can start working on this.

**Comment by rain1024** [comment]
Chào @duyluandethuong 

Đối với từng nhiệm vụ, underthesea đều có một project riêng để huấn luyện model. 

Nhóm mình để đường dẫn tới project ở phần custom models

![selection_001](https://user-images.githubusercontent.com/1780281/37511238-aac91ca4-2930-11e8-8e69-de132d8f5c84.png)

Với bài toán sentiment, bạn tham khảo dự án `undertheseanlp/sentiment` nhé https://github.com/undertheseanlp/sentiment

**Comment by duyluandethuong** [comment]
Cảm ơn team nhé
