### ISSUE TITLE
custom Model in Vietnamese Named Entity Recognition

### ISSUE THREAD

**Issue by khanhmd58** [magizbox/underthesea#178]
when it run main.py  in NER  underthesea
i was error    : 
from preprocess import vlsp2016
ImportError: No module named 'preprocess'

please help me..:(

**Comment by rain1024** [comment]
@khanhmd58: mình nghĩ issue này nên mở ở project https://github.com/undertheseanlp/ner thì hợp lý hơn

**Comment by khanhmd58** [comment]
dạ vâng anh vũ để em tạo issue ở đấy ạ
