### ISSUE TITLE
Updating project link in NLP Tools Wiki

### ISSUE THREAD

**Issue by suicao** [magizbox/underthesea#186]
Hi guys, I' m the author of the [suicao/vn-accent-restoration](https://gitlab.com/suicao/vn-accent-restoration) tool in the Wiki. Recently I moved the project to github which means the linked one was no longer maintained. Could you kindly update the Wiki to point to the new one at [suicao/Vn-Accent-Restorer](https://github.com/suicao/Vn-Accent-Restorer)?

Many thanks for your contributions to the NLP community.

Khoi Nguyen.

**Comment by rain1024** [comment]
Hi @suicao, your project is updated in wiki.

I wish the project every success.
