### ISSUE TITLE
relations between pos, chunk and ner

### ISSUE THREAD

**Issue by dattx0** [magizbox/underthesea#187]
Thanks for this project! I have some questions: 1) what relations between pos, chunk and ner, how to use pos and chunk features to predict ner tag? (using embedding and concatenate them like word + char embedding in the current bilstm-crf model?)  2) how to get all pos and chunk tags (from this project and vlsp2016, should using unknown label)? Thanks for answering! Ps: Can you give some instructions and tutorials to learn nlp?

**Comment by rain1024** [comment]
Hi @dattx0 ,

I don't understand your first question clearly, do you mean you want using pos, chunk feature to predict ner tag in deep learning models?

About your second question, please visit these links [Mô tả dữ liệu bài toán POS Tag](https://github.com/magizbox/underthesea/wiki/M%C3%B4-t%E1%BA%A3-d%E1%BB%AF-li%E1%BB%87u-b%C3%A0i-to%C3%A1n-POS-Tag) and [Mô tả dữ liệu bài toán Chunking](https://github.com/magizbox/underthesea/wiki/M%C3%B4-t%E1%BA%A3-d%E1%BB%AF-li%E1%BB%87u-b%C3%A0i-to%C3%A1n-Chunking). Its contain all information about pos tags and chunking tags.

[This question in quora](https://www.quora.com/What-are-the-best-resources-to-learn-NLP-books-videos-websites-papers ) is same with your last question, and it is already have many good questions about resources to learn NLP. Hope it will help you.

**Comment by dattx0** [comment]
thank you, I want use pos and chunk to predict ner tag. I think it can be embedded and concatenate to word represents like char embedding.

**Comment by suicao** [comment]
@dattx0 Are you trying to implement  [this paper](https://arxiv.org/abs/1705.10610).

The authors indeed didn't describe exactly how they embedded the POS and Chunking features to a vector space. My guess is they replaced the words in the training corpus by their respective POS/Chunking tags and performed  word2vec or a similar algorithm on the new data to get the tag embeddings.

**Comment by suicao** [comment]
From that paper's repo I think all the pos and chunking features were initialized randomly and learned on the fly.
