### ISSUE TITLE
How can i train my model from csv file?

### ISSUE THREAD

**Issue by hoabuiduy** [magizbox/underthesea#191]
I have csv file for text classification. How can i train them and make new model?

Please help me :)

Thanks all you guys!

**Comment by rain1024** [comment]
@hoabuiduy can you give some samples of your dataset?

**Comment by hoabuiduy** [comment]
Hi, my dataset about Ecommerce. I got from Lazada

I would like to classify product category

Please check file by attached
[datafeed.zip](https://github.com/magizbox/underthesea/files/2280418/datafeed.zip)

**Comment by rain1024** [comment]
This issue will be moved to https://github.com/undertheseanlp/classification/issues/6
